# Generated by Django 4.2.6 on 2023-12-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioSegments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="static/media")),
                ("customer", models.CharField(max_length=30)),
                ("field", models.CharField(max_length=20)),
                ("status", models.CharField(default="new")),
                ("transcript", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="static/media")),
                ("customer", models.CharField(max_length=30)),
                ("field", models.CharField(max_length=20)),
                ("status", models.CharField(default="new")),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audiobatvoice.audiosegments",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
