# Generated by Django 4.2.6 on 2023-12-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Audio",
        ),
        migrations.DeleteModel(
            name="AudioSegments",
        ),
    ]
