# Generated by Django 5.0 on 2023-12-10 03:47

import audiobatvoice.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0005_alter_audiosegment_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="title",
            field=models.CharField(default="new", max_length=50),
        ),
        migrations.AlterField(
            model_name="audiosegment",
            name="transcript",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    audiobatvoice.validators.check_character_set,
                    audiobatvoice.validators.check_space,
                    audiobatvoice.validators.check_capital_letters,
                    audiobatvoice.validators.check_the_end_text,
                ],
            ),
        ),
    ]
