# Generated by Django 5.0 on 2023-12-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0006_audio_title_alter_audiosegment_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
