# Generated by Django 5.0 on 2023-12-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0007_audio_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
