# Generated by Django 5.0 on 2023-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0008_alter_audio_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="length",
            field=models.IntegerField(null=True),
        ),
    ]
