# Generated by Django 5.0 on 2023-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0010_alter_audio_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegment",
            name="length",
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="audio",
            name="length",
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
