# Generated by Django 5.0 on 2023-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0011_audiosegment_length_alter_audio_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiosegment",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
