# Generated by Django 5.0 on 2023-12-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0012_alter_audio_length_alter_audiosegment_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="slug",
        ),
    ]
