# Generated by Django 5.0 on 2023-12-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiobatvoice", "0013_remove_audio_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
